# Generated by Django 3.0.3 on 2020-04-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0047_auto_20200326_0553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profilepic',
            new_name='Profile_pic',
        ),
        migrations.RenameField(
            model_name='match_class',
            old_name='match',
            new_name='who_matched',
        ),
        migrations.RenameField(
            model_name='match_class',
            old_name='youself',
            new_name='who_request',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='fullname',
            new_name='firstname',
        ),
    ]
