# Generated by Django 3.0.3 on 2020-04-11 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0048_auto_20200411_1735'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_pic',
            new_name='Profile_Picture',
        ),
        migrations.RenameField(
            model_name='match_class',
            old_name='who_matched',
            new_name='another_user',
        ),
        migrations.RenameField(
            model_name='match_class',
            old_name='who_request',
            new_name='myself',
        ),
        migrations.RenameField(
            model_name='request_class',
            old_name='request_list',
            new_name='who_recive',
        ),
        migrations.RenameField(
            model_name='request_class',
            old_name='whorecive',
            new_name='who_send',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tinderforeduapp.UserInfo'),
        ),
        migrations.AlterField(
            model_name='profile_picture',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tinderforeduapp.UserInfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='match',
            field=models.ManyToManyField(blank=True, to='tinderforeduapp.Match_Class'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='request',
            field=models.ManyToManyField(blank=True, to='tinderforeduapp.Request_Class'),
        ),
    ]
