# Generated by Django 3.0.3 on 2020-04-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200216_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Savechat',
            new_name='Chatroom',
        ),
    ]
