# Generated by Django 3.0.3 on 2020-04-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200415_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='url_room_name',
            new_name='room_name',
        ),
    ]
